# Generated by Django 5.1.1 on 2024-09-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='itemid',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='itemName',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='itemPrice',
            new_name='item_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='itemDescription',
        ),
        migrations.AddField(
            model_name='product',
            name='item_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
